name: Trivy IaC Scan (CloudFormation)

on:
  push:
    branches:
      - iac-security
  workflow_dispatch:

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy IaC scan
        uses: aquasecurity/trivy-action@v2
        with:
          scan-type: "config"
          scan-ref: "."
          severity: "CRITICAL,HIGH,MEDIUM"
          format: "table"
          exit-code: "0"
