
name: Scans and Images (MAIN)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # IaC Security Scan
      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL,HIGH,MEDIUM
          format: sarif
          output: trivy-iac-results.sarif
          exit-code: "0"

      - name: Upload IaC SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-sarif-report
          path: trivy-iac-results.sarif

      # Container Security Scan
      - name: Container Security Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: image
          image-ref: riyazmanandhar/juice-shop:latest
          severity: CRITICAL,HIGH,MEDIUM
          format: sarif
          output: trivy-container-results.sarif
          exit-code: "0"

      - name: Upload Container Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-container-sarif
          path: trivy-container-results.sarif

      # SSH into EC2
      - name: SSH into EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 54.235.194.192 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_ed25519 ubuntu@54.235.194.192 "echo 'SSH connection successful!'"