name: IaC Security Scan (Pipeline)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # IaC Security Scan using Trivy
      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL,HIGH,MEDIUM
          format: sarif
          output: trivy-iac-results.sarif

      # Upload SARIF Report
      - name: Upload IaC SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-sarif-report
          path: trivy-iac-results.sarif


  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Login to Docker Hub
  #       run: |
  #         docker login -u riyazmanandhar -p $DOCKERHUB_PAT
  #       env:
  #         DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

  #     - name: Build Docker image
  #       run: |
  #         docker build -t riyazmanandhar/juice-shop:latest .

  #     - name: Push Docker image
  #       run: |
  #         docker push riyazmanandhar/juice-shop:latest
